---
title: "atpase_analysis"
author: "Matt George"
output: html_document
date: "2022-07-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages; set ggplot theme
```{r message=FALSE, warning=FALSE}
## clear workspace
rm(list=ls())

## Load Packages
load.lib<-c("readxl","tidyverse","bestNormalize","agricolae","nlme","multcomp","rstatix") # List of required packages
install.lib <- load.lib[!load.lib %in% installed.packages()] # Select missing packages
for(lib in install.lib) install.packages(lib,dependencies=TRUE) # Install missing packages + dependencies
sapply(load.lib,require,character=TRUE) # Load all packages.

## Set ggplot theme
my_theme <- theme(line              = element_line(size=1.2),
                  rect              = element_rect(size=1.2),
                  text              = element_text(size=14,color="black"),
                  panel.background  = element_blank(),
                  panel.grid.major  = element_blank(), 
                  panel.grid.minor  = element_blank(),
                  axis.text.x       = element_text(size=16,color="black"), #,angle=90),
                  axis.text.y       = element_text(size=16,color="black"),
                  axis.title.x      = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
                  axis.title.y      = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
                  axis.ticks.x      = element_line(color="black"),
                  axis.ticks.y      = element_line(color="black"),
                  # axis.line         = element_line(color = "black", size = 0.1),
                  panel.border      = element_rect(color = "black", fill=NA, size=1.2),
                  legend.key        = element_blank(), # removes background of legend bullets
                  legend.position   = "none"
                  ) 
```


LOAD dataset
```{r}
getwd()
atpase_plot     <- read_excel("ATPase/ATPase.xlsx",
                              sheet = "ATPase", col_names = TRUE)
trt_list        <- read_excel("ATPase/ATPase.xlsx", 
                              sheet = "trt_list", col_names = TRUE)
atpase_plot$trt_list  <- factor(atpase_plot$trt_list,  levels = trt_list$trt_list         , ordered=TRUE)
atpase_plot$timepoint <- factor(atpase_plot$timepoint, levels = c("-10","1","2","5","6","10","11","12") , ordered=TRUE)

# set alpha for boxplots
alpha_set = 0.8

# summarize by ploidy * timepoint * treatment
atpase_plot %>% group_by(trt_list) %>% summarise(mean=mean(ATPase), sd=sd(ATPase), count=n())

```

boxplots, controls
```{r}
atpase_plot_controls <- atpase_plot %>% filter(trt == "control")
trt_list_controls  <- trt_list %>% filter(trt == "control")


bp1 <-  ggplot(atpase_plot_controls, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_controls$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp1

ggsave("analyses/atpase/bp_atpase_controls.png",
       plot   = bp1,
       dpi    = 600,
       device = "png",
       width  = 3*1.2,
       height = 4*1.2,
       units  = "in")

```

boxplots, diploids - treatment only
```{r}
atpase_plot_diploids <- atpase_plot %>% filter(trt_list == "D_heat_only_1"   |
                                               trt_list == "D_heat_only_5"   |
                                               trt_list == "D_heat_only_10"  |
                                               trt_list == "D_heat_desiccation_2"   |
                                               trt_list == "D_heat_desiccation_6"   |
                                               trt_list == "D_heat_desiccation_11")
trt_list_diploids  <- trt_list %>% filter(     trt_list == "D_heat_only_1"   |
                                               trt_list == "D_heat_only_5"   |
                                               trt_list == "D_heat_only_10"  |
                                               trt_list == "D_heat_desiccation_2"   |
                                               trt_list == "D_heat_desiccation_6"   |
                                               trt_list == "D_heat_desiccation_11")

atpase_plot_diploids$trt_list <- factor(atpase_plot_diploids$trt_list , 
                                        levels = c("D_heat_only_1","D_heat_only_5","D_heat_only_10","D_heat_desiccation_2",
                                                   "D_heat_desiccation_6","D_heat_desiccation_11") , 
                                        ordered=TRUE)

bp2 <-  ggplot(atpase_plot_diploids, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        # geom_point(aes(x=as.factor(timepoint), y=SMR_weight, group=as.factor(trt_list)),
        #            position=position_dodge(width=0.75),
        #            size = 3, shape = 19, fill = "black", alpha = 1/10) +
        scale_fill_manual(values=trt_list_diploids$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp2

ggsave("analyses/atpase/bp_atpase_diploids.png",
       plot   = bp2,
       dpi    = 600,
       device = "png",
       width  = 4.5,
       height = 4,
       units  = "in")

```

boxplots, triploids - treatment only
```{r}
atpase_plot_triploids <- atpase_plot %>% filter(trt_list == "T_heat_only_1"   |
                                                trt_list == "T_heat_only_5"   |
                                                trt_list == "T_heat_only_10"  |
                                                trt_list == "T_heat_desiccation_2"   |
                                                trt_list == "T_heat_desiccation_5"   |
                                                trt_list == "T_heat_desiccation_10")
trt_list_triploids  <- trt_list %>% filter(     trt_list == "T_heat_only_1"   |
                                                trt_list == "T_heat_only_5"   |
                                                trt_list == "T_heat_only_10"  |
                                                trt_list == "T_heat_desiccation_2"   |
                                                trt_list == "T_heat_desiccation_6"   |
                                                trt_list == "T_heat_desiccation_11")

atpase_plot_triploids$trt_list <- factor(atpase_plot_triploids$trt_list , 
                                        levels = c("T_heat_only_1","T_heat_only_5","T_heat_only_10","T_heat_desiccation_2",
                                                   "T_heat_desiccation_5","T_heat_desiccation_10") , 
                                        ordered=TRUE)


bp3 <-  ggplot(atpase_plot_triploids, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_triploids$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp3

ggsave("analyses/atpase/bp_atpase_triploids.png",
       plot   = bp3,
       dpi    = 600,
       device = "png",
       width  = 4.5,
       height = 4,
       units  = "in")

```
boxplots, heat only - both ploidy
```{r}
atpase_plot_heat <- atpase_plot %>% filter(    
                                               trt_list == "D_heat_only_1"   |
                                               trt_list == "D_heat_only_5"   |
                                               trt_list == "D_heat_only_10"  |
                                               trt_list == "T_heat_only_1"   |
                                               trt_list == "T_heat_only_5"   |
                                               trt_list == "T_heat_only_10")
trt_list_heat  <- trt_list %>% filter(         
                                               trt_list == "D_heat_only_1"   |
                                               trt_list == "D_heat_only_5"   |
                                               trt_list == "D_heat_only_10"  |
                                               trt_list == "T_heat_only_1"   |
                                               trt_list == "T_heat_only_5"   |
                                               trt_list == "T_heat_only_10")


bp4 <-  ggplot(atpase_plot_heat, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_heat$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp4

ggsave("analyses/atpase/bp_atpase_heat.png",
       plot   = bp4,
       dpi    = 600,
       device = "png",
       width  = 4.5,
       height = 4,
       units  = "in")

```

boxplots, desiccation only - both ploidy
```{r}
atpase_plot_desiccation <- atpase_plot %>% filter(    
                                                   trt_list == "D_heat_desiccation_2"   |
                                                   trt_list == "D_heat_desiccation_6"   |
                                                   trt_list == "D_heat_desiccation_11"  |
                                                   trt_list == "T_heat_desiccation_2"   |
                                                   trt_list == "T_heat_desiccation_6"   |
                                                   trt_list == "T_heat_desiccation_11")
trt_list_desiccation  <- trt_list %>% filter( 
                                               trt_list == "D_heat_desiccation_2"   |
                                               trt_list == "D_heat_desiccation_6"   |
                                               trt_list == "D_heat_desiccation_11"  |
                                               trt_list == "T_heat_desiccation_2"   |
                                               trt_list == "T_heat_desiccation_6"   |
                                               trt_list == "T_heat_desiccation_11")


bp5 <-  ggplot(atpase_plot_desiccation, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_desiccation$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp5

ggsave("analyses/atpase/bp_atpase_desiccation.png",
       plot   = bp5,
       dpi    = 600,
       device = "png",
       width  = 4.5,
       height = 4,
       units  = "in")

```

boxplots, all trt - both ploidy
```{r}
atpase_plot_all <- atpase_plot %>% filter(         trt_list == "D_control_-10"          |
                                                   trt_list == "T_control_-10"          |   
                                                   trt_list == "D_heat_only_1"          |
                                                   trt_list == "T_heat_only_1"          |
                                                   trt_list == "D_heat_only_5"          |
                                                   trt_list == "T_heat_only_5"          |                                                                                                   trt_list == "D_heat_only_10"         |
                                                   trt_list == "T_heat_only_10"         |                                                                                                   trt_list == "D_heat_desiccation_2"   |                                                                                                   trt_list == "T_heat_desiccation_2"   |
                                                   trt_list == "D_heat_desiccation_6"   |
                                                   trt_list == "T_heat_desiccation_6"   |                                                                                                   trt_list == "D_heat_desiccation_11"  |
                                                   trt_list == "T_heat_desiccation_11"  |
                                                   trt_list == "D_control_12"           |
                                                   trt_list == "T_control_12")

trt_list_all  <- trt_list %>% filter(              trt_list == "D_control_-10"          |
                                                   trt_list == "T_control_-10"          |   
                                                   trt_list == "D_heat_only_1"          |
                                                   trt_list == "T_heat_only_1"          |
                                                   trt_list == "D_heat_only_5"          |
                                                   trt_list == "T_heat_only_5"          |                                                                                                   trt_list == "D_heat_only_10"         |
                                                   trt_list == "T_heat_only_10"         |                                                                                                   trt_list == "D_heat_desiccation_2"   |                                                                                                   trt_list == "T_heat_desiccation_2"   |
                                                   trt_list == "D_heat_desiccation_6"   |
                                                   trt_list == "T_heat_desiccation_6"   |                                                                                                   trt_list == "D_heat_desiccation_11"  |
                                                   trt_list == "T_heat_desiccation_11"  |
                                                   trt_list == "D_control_12"           |
                                                   trt_list == "T_control_12")


bp6 <-  ggplot(atpase_plot_all, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_all$trt_colors) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp6

ggsave("analyses/atpase/bp_atpase_all.png",
       plot   = bp6,
       dpi    = 1200,
       device = "png",
       width  = 6.5,
       height = 4,
       units  = "in")

```

### linegraph, overview of main result
```{r}
atpase_plot_all <- atpase_plot %>% filter(         trt_list == "D_control_-10"          |
                                                   trt_list == "T_control_-10"          |   
                                                   trt_list == "D_heat_only_1"          |
                                                   trt_list == "T_heat_only_1"          |                                                                                                             trt_list == "D_heat_desiccation_2"   |                                                                                                             trt_list == "T_heat_desiccation_2")

trt_list_all  <- trt_list %>% filter(              trt_list == "D_control_-10"          |
                                                   trt_list == "T_control_-10"          |   
                                                   trt_list == "D_heat_only_1"          |
                                                   trt_list == "T_heat_only_1"          |                                                                                                             trt_list == "D_heat_desiccation_2"   |                                                                                                             trt_list == "T_heat_desiccation_2")


bp7 <-  ggplot(atpase_plot_all, aes(x=as.factor(timepoint), y=ATPase, 
                                       group=as.factor(trt_list), fill=trt_list)) +
        geom_boxplot(colour = "black", size = 0.8,outlier.colour="black", outlier.shape = 16,
                     outlier.size=1, notch=FALSE, varwidth = TRUE, alpha = alpha_set) +
        scale_fill_manual(values=trt_list_all$trt_colors_overview) +
        scale_y_continuous(breaks = seq(0, 10, 2), limits = c(0, 10.5)) +
        # scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0, 32)) + 
        my_theme

bp7

ggsave("analyses/atpase/bp_atpase_overview.png",
       plot   = bp7,
       dpi    = 1200,
       device = "png",
       width  = 4.5,
       height = 4,
       units  = "in")

```

Statistical Testing
```{R}
atpase_plot     <- read_excel("ATPase/ATPase.xlsx",
                              sheet = "stat", col_names = TRUE)
dat_stat <- atpase_plot_all
test_me <- dat_stat$ATPase

dat_stat$ID         <- factor(dat_stat$ID)
dat_stat$trt        <- factor(dat_stat$trt)
dat_stat$ploidy     <- factor(dat_stat$ploidy)
dat_stat$timepoint  <- factor(dat_stat$timepoint)

qqnorm(test_me) # check linearity of transformed data
qqline(test_me)
norm_test <- shapiro.test(test_me) # p-value fail = good, don't need transformation
print(norm_test$p.value)

if(norm_test$p.value<0.05)     {
        normalized <- bestNormalize(test_me)
        test_me <- normalized$x.t # overwrite
        qqnorm(test_me) # check linearity of transformed data
        qqline(test_me)
        print(shapiro.test(test_me))
        print("transformed!",quote=FALSE)}

dat_stat$response <- test_me 

my_test <- aov(response ~ ploidy * timepoint * trt, data = dat_stat)

my_test_summary <- summary(my_test)
summary(my_test)

tx <- with(dat_stat, interaction(timepoint,trt,ploidy))
amod <- aov(response ~ tx, data = dat_stat)
mult_comp <- HSD.test(amod, "tx", group=TRUE, console=TRUE)

write.table(my_test_summary[[1]],                      file = "stats/AOV_atpase.csv",      row.names = TRUE)
write.table(mult_comp$groups,                     file = "stats/HSD_test_atpase.csv", row.names = TRUE)


```






