---
title: "histology_analysis"
author: "Matt George"
output: html_document
date: "2022-08-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages; set ggplot theme
```{r message=FALSE, warning=FALSE}
## clear workspace
rm(list=ls())

## Load Packages
load.lib<-c("readxl","tidyverse","bestNormalize","agricolae","nlme","multcomp","rstatix","ggpubr","RColorBrewer") # List of required packages
install.lib <- load.lib[!load.lib %in% installed.packages()] # Select missing packages
for(lib in install.lib) install.packages(lib,dependencies=TRUE) # Install missing packages + dependencies
sapply(load.lib,require,character=TRUE) # Load all packages.

## Set ggplot theme
my_theme <- theme(line              = element_line(size=1.2),
                  rect              = element_rect(size=1.2),
                  text              = element_text(size=14,color="black"),
                  panel.background  = element_blank(),
                  panel.grid.major  = element_blank(), 
                  panel.grid.minor  = element_blank(),
                  axis.text.x       = element_text(size=16,color="black"), #,angle=90),
                  axis.text.y       = element_text(size=16,color="black"),
                  axis.title.x      = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
                  axis.title.y      = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
                  axis.ticks.x      = element_line(color="black"),
                  axis.ticks.y      = element_line(color="black"),
                  # axis.line         = element_line(color = "black", size = 0.1),
                  panel.border      = element_rect(color = "black", fill=NA, size=1.2),
                  legend.key        = element_blank(), # removes background of legend bullets
                  legend.position   = "none"
                  ) 
```


### LOAD dataset
```{r}
getwd()
tank_plot     <- read_excel("desiccation/20210713_EXP2/tank_temps.xlsx",
                              sheet = "combo", col_names = TRUE)
oyster_plot   <- read_excel("desiccation/20210713_EXP2/oyster_internal_temps.xlsx",
                              sheet = "max", col_names = TRUE)
```

tank conditions plot 
```{r}

tank_conditions  <- tank_plot %>% filter(group == "tank")
oyster_temp      <- tank_plot %>% filter(group == "oysters")

p1 <- ggplot(data=tank_plot) +
            geom_smooth(aes(x=hour,
                            y=humid_mean/2.5, 
                            ymin=humid_mean/2.5-humid_se,
                            ymax=humid_mean/2.5+humid_se,
                            group="humidity",
                            color="humidity")) +  
            geom_smooth(aes(x=hour,
                            y=temp_mean, 
                            ymin=temp_mean-temp_se,
                            ymax=temp_mean+temp_se,
                            group=group,
                            color=group)) +
            scale_y_continuous(breaks = seq(10, 60, 10), limits = c(8, 52), 
                               sec.axis = sec_axis(trans=~.*2.5, name="Second Axis", 
                                                   breaks = seq(25, 100, 25))) +
            scale_x_continuous(breaks = seq(1, 6, 1)) +
            scale_color_manual(values=c("darkorange","seagreen3","orangered2")) +
            # scale_x_datetime(breaks = date_breaks("1 hour"),labels=date_format("%H:%M"))+ 
            # scale_x_date(date_labels = "%b/%d") +
            my_theme

p1

ggsave("analyses/desiccation/tank_conditions.png",
       plot   = p1,
       dpi    = 1200,
       device = "png",
       width  = 5,
       height = 4,
       units  = "in")

```


Statistical Testing
```{R}

p2 <- ggplot(oyster_plot, aes(x=shell_volume, y=max_temp)) +
      geom_point() +
      geom_smooth(method = "lm", formula = y ~ x) +
      # geom_line(size=1) +
      # scale_color_manual(values=c("royalblue1","orangered1")) +
      scale_y_continuous(breaks = seq(10, 60, 10), limits = c(20, 60)) +
      scale_x_continuous(breaks = seq(60, 140, 20), limits = c(50, 150)) + 
      my_theme

p2

ggsave("analyses/desiccation/max_temp.png",
       plot   = p2,
       dpi    = 1200,
       device = "png",
       width  = 5,
       height = 5,
       units  = "in")


```






