---
title: "2_DESeq_analysis"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = FALSE, cache = TRUE)
```

### Load libraries
```{r load_libraries, inlcude = TRUE}

## Install Rtools directly from (https://cran.r-project.org/bin/windows/Rtools/), then install these on first run:
# install.packages("BiocManager")
# BiocManager::install("DESeq2")
# BiocManager::install("vsn")
# BiocManager::install("tidybulk")
# BiocManager::install("goseq")
# BiocManager::install("affycoretools")
# BiocManager::install("EnhancedVolcano")
# BiocManager::install("pcaExplorer")
# BiocManager::install("apeglm")


# List of packages we want to install (run every time)
load.lib<-c("DESeq2","edgeR","goseq","dplyr","GenomicFeatures","data.table","calibrate","affycoretools","data.table","vsn","tidybulk","ggplot2","cowplot","pheatmap","gplots","RColorBrewer","EnhancedVolcano","pcaExplorer","readxl","apeglm","ashr")

# Select only the packages that aren't currently installed (run every time)
install.lib <- load.lib[!load.lib %in% installed.packages()]

# And finally we install the missing packages, including their dependency.
for(lib in install.lib) install.packages(lib,dependencies=TRUE)
# After the installation process completes, we load all packages.
sapply(load.lib,require,character=TRUE)
                        
```

#Set ggplot theme
```{r ggplot_theme, include=FALSE}

my_theme <- theme(line              = element_line(size=1.5),
                  rect              = element_rect(size=1.5),
                  text              = element_text(size=14,color="black"),
                  panel.background  = element_blank(),
                  panel.grid.major  = element_blank(), 
                  panel.grid.minor  = element_blank(),
                  axis.text.x       = element_text(size=16,color="black"),
                  axis.text.y       = element_text(size=16,color="black"),
                  axis.title.x      = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)),
                  axis.title.y      = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
                  axis.ticks.x      = element_line(color="black"),
                  axis.ticks.y      = element_line(color="black"),
                  # axis.line         = element_line(color = "black", size = 0.1),
                  panel.border      = element_rect(color = "black", fill=NA, size=1.5),
                  legend.key        = element_blank()) # removes background of legend bullets
```

#Load data
```{r load_data, inlcude = TRUE}
print(getwd())  # working directory 
cts <- as.matrix(read.csv("../data/20220608_gene_count_matrix.csv", sep=',', header=TRUE, row.names = "gene_id"))

# Import experimental design information
trt_list <- read.csv("../data/treatments.csv", sep=',', header=TRUE, row.names = "ID")
coldata <- trt_list[,c("ploidy","condition")]
colnames(cts) <- row.names(trt_list) #!make sure column and row names for coldata and cts match
coldata$ploidy <- factor(coldata$ploidy)
coldata$condition <- factor(coldata$condition)
coldata$group <- factor(trt_list$group)

coldata <- coldata %>% filter(group == "C" | group == "D")
cts <- subset(cts, select=row.names(coldata))

```
# DESeq condition and ploidy w/o interaction
```{r load_data, inlcude = TRUE}
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ ploidy)

dds 

dds <- DESeq(dds)
resultsNames(dds) # lists the coefficients

```
```{r calculate fold-change, include=False}
# Break up - fold change only
# res_all        <- results(dds)
res_ploidy     <- results(dds, name="ploidy_triploid_vs_diploid"       )
# res_cond_heat  <- results(dds, name="condition_heat_vs_control"        )
# res_cond_des   <- results(dds, name="condition_desiccation_vs_control" )
```

```{r summary statistics, include=TRUE}

# resOrdered <- res[order(res$pvalue),] #order by smallest p value 

# summary(res_all)
summary(res_ploidy)                       # up (15%), down (9.3%)
# summary(res_cond_heat)                    # up (6.2%), down (4.2%)
# summary(res_cond_des)                     # up (3.4%), down (2.9%)

# sum(res_all$padj < 0.1, na.rm=TRUE)       # 
sum(res_ploidy$padj < 0.1, na.rm=TRUE)      # 7516
# sum(res_cond_heat$padj < 0.1, na.rm=TRUE) # 
# sum(res_cond_des$padj < 0.1, na.rm=TRUE)  # 

```


```{r compare LFC shrinkage methods, include=TRUE}
res_ploidy_a     <- lfcShrink(dds, coef="ploidy_triploid_vs_diploid"       ,type="apeglm")
res_ploidy_b     <- lfcShrink(dds, coef="ploidy_triploid_vs_diploid"       ,type="normal")
res_ploidy_c     <- lfcShrink(dds, coef="ploidy_triploid_vs_diploid"       ,type="ashr")
# 
# res_cond_heat_a  <- lfcShrink(dds, coef="condition_heat_vs_control"        ,type="apeglm")
# res_cond_heat_b  <- lfcShrink(dds, coef="condition_heat_vs_control"        ,type="normal")
# res_cond_heat_c  <- lfcShrink(dds, coef="condition_heat_vs_control"        ,type="ashr")
# 
# res_cond_des_a   <- lfcShrink(dds, coef="condition_desiccation_vs_control" ,type="apeglm")
# res_cond_des_b   <- lfcShrink(dds, coef="condition_desiccation_vs_control" ,type="normal")
# res_cond_des_c   <- lfcShrink(dds, coef="condition_desiccation_vs_control" ,type="ashr")

par(mfrow=c(1,3), mar=c(4,4,2,1))
xlim <- c(1,1e5); ylim <- c(-3,3)
DESeq2::plotMA(res_ploidy_a, xlim=xlim, ylim=ylim, main="ploidy: apeglm")
DESeq2::plotMA(res_ploidy_b, xlim=xlim, ylim=ylim, main="ploidy: normal")
DESeq2::plotMA(res_ploidy_c, xlim=xlim, ylim=ylim, main="ploidy: ashr")

# par(mfrow=c(1,3), mar=c(4,4,2,1))
# xlim <- c(1,1e5); ylim <- c(-3,3)
# DESeq2::plotMA(res_cond_heat_a, xlim=xlim, ylim=ylim, main="Heat: apeglm")
# DESeq2::plotMA(res_cond_heat_b, xlim=xlim, ylim=ylim, main="Heat: normal")
# DESeq2::plotMA(res_cond_heat_c, xlim=xlim, ylim=ylim, main="Heat: ashr")
# 
# par(mfrow=c(1,3), mar=c(4,4,2,1))
# xlim <- c(1,1e5); ylim <- c(-3,3)
# DESeq2::plotMA(res_cond_des_a, xlim=xlim, ylim=ylim, main="Desiccation: apeglm")
# DESeq2::plotMA(res_cond_des_b, xlim=xlim, ylim=ylim, main="Desiccation: normal")
# DESeq2::plotMA(res_cond_des_c, xlim=xlim, ylim=ylim, main="Desiccation: ashr")

```

```{r plot counts for a single gene, include=TRUE}
d <- plotCounts(dds, gene=which.min(res_all$padj), intgroup="ploidy", 
                returnData=TRUE)
ggplot(d, aes(x=ploidy, y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0)) + 
  scale_y_log10(breaks=c(25,100,400))

```


```{r subset by significant, export, include=TRUE}

resOrdered <- res_ploidy_c[order(res_ploidy_c$pvalue),]

resSig <- subset(resOrdered, padj < 0.1)
resSig

sum(resSig$padj < 0.1, na.rm=TRUE)

# write.csv(as.data.frame(resSig), 
#           file="../output/ploidy_significant_genes.csv")


```

```{r pca, include=FALSE}
pcaExplorer(dds = dds)

```
