---
title: "3_generate_gene_tables"
author: "Matt George; mngeorge@uw.edu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = FALSE, cache = TRUE)
```

```{bash, engine.opts='-l'}
echo $PATH
```


### Load libraries
```{r load_libraries, inlcude = TRUE}

# List of packages we want to install (run every time)
load.lib<-c("ggplot2","RColorBrewer","readxl","ggpubr","tidyverse","tibble","stringr","kmisc")

# Select only the packages that aren't currently installed (run every time)
install.lib <- load.lib[!load.lib %in% installed.packages()]

# And finally we install the missing packages, including their dependency.
for(lib in install.lib) install.packages(lib,dependencies=TRUE)
# After the installation process completes, we load all packages.
sapply(load.lib,require,character=TRUE)

                        
```

#Load data
```{r load_data, inlcude = TRUE}

# Load LOCID to gene description tables, compare, find gigas and mito genes
control_ploidy <- read.delim("../output/control_ploidy/CONTROL_PLOIDY-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
control_ploidy <- control_ploidy %>% select(gene, log2FoldChange, description)

heat_ploidy <- read.delim("../output/heat_ploidy/HEAT_PLOIDY-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
heat_ploidy <- heat_ploidy %>% select(gene, log2FoldChange, description)

desiccation_ploidy <- read.delim("../output/desiccation_ploidy/DESICCATION_PLOIDY-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
desiccation_ploidy <- desiccation_ploidy %>% select(gene, log2FoldChange, description)

diploid_heat <- read.delim("../output/diploid_heat/DIPLOID_HEAT-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
diploid_heat <- diploid_heat %>% select(gene, log2FoldChange, description)

diploid_desiccation <- read.delim("../output/diploid_desiccation/DIPLOID_DESICCATION-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
diploid_desiccation <- diploid_desiccation %>% select(gene, log2FoldChange, description)

triploid_heat <- read.delim("../output/triploid_heat/TRIPLOID_HEAT-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
triploid_heat <- triploid_heat %>% select(gene, log2FoldChange, description)

triploid_desiccation <- read.delim("../output/triploid_desiccation/TRIPLOID_DESICCATION-SIG-DEG-apeglm.csv", sep = " ", header = TRUE)
triploid_desiccation <- triploid_desiccation %>% select(gene, log2FoldChange, description)

```

# Separate tables by unknown LOCID
```{r}

grx <- glob2rx("unchar*")


control_ploidy_NA              <- with(control_ploidy,       subset(control_ploidy,       subset = grepl(glob2rx("LOCNA*"), gene)))
control_ploidy                 <- anti_join(control_ploidy, control_ploidy_NA, by = 'gene')
control_ploidy_uncharacterized <- with(control_ploidy, subset(control_ploidy, subset = grepl(grx, description)))
control_ploidy_characterized   <- anti_join(control_ploidy, control_ploidy_uncharacterized, by = 'gene')

heat_ploidy_NA              <- with(heat_ploidy,          subset(heat_ploidy,          subset = grepl(glob2rx("LOCNA*"), gene)))
heat_ploidy                 <- anti_join(heat_ploidy, heat_ploidy_NA, by = 'gene')
heat_ploidy_uncharacterized <- with(heat_ploidy, subset(heat_ploidy, subset = grepl(grx, description)))
heat_ploidy_characterized   <- anti_join(heat_ploidy, heat_ploidy_uncharacterized, by = 'gene')

desiccation_ploidy_NA              <- with(desiccation_ploidy,   subset(desiccation_ploidy,   subset = grepl(glob2rx("LOCNA*"), gene)))
desiccation_ploidy                 <- anti_join(desiccation_ploidy, desiccation_ploidy_NA, by = 'gene')
desiccation_ploidy_uncharacterized <- with(desiccation_ploidy, subset(desiccation_ploidy, subset = grepl(grx, description)))
desiccation_ploidy_characterized   <- anti_join(desiccation_ploidy, desiccation_ploidy_uncharacterized, by = 'gene')

diploid_heat_NA              <- with(diploid_heat ,        subset(diploid_heat,         subset = grepl(glob2rx("LOCNA*"), gene)))
diploid_heat                 <- anti_join(diploid_heat, diploid_heat_NA, by = 'gene')
diploid_heat_uncharacterized <- with(diploid_heat, subset(diploid_heat, subset = grepl(grx, description)))
diploid_heat_characterized   <- anti_join(diploid_heat, diploid_heat_uncharacterized, by = 'gene')

diploid_desiccation_NA              <- with(diploid_desiccation,  subset(diploid_desiccation,  subset = grepl(glob2rx("LOCNA*"), gene)))
diploid_desiccation                 <- anti_join(diploid_desiccation, diploid_desiccation_NA, by = 'gene')
diploid_desiccation_uncharacterized <- with(diploid_desiccation, subset(diploid_desiccation, subset = grepl(grx, description)))
diploid_desiccation_characterized   <- anti_join(diploid_desiccation, diploid_desiccation_uncharacterized, by = 'gene')

triploid_heat_NA              <- with(triploid_heat,        subset(triploid_heat,        subset = grepl(glob2rx("LOCNA*"), gene)))
triploid_heat                 <- anti_join(triploid_heat, triploid_heat_NA, by = 'gene')
triploid_heat_uncharacterized <- with(triploid_heat, subset(triploid_heat, subset = grepl(grx, description)))
triploid_heat_characterized   <- anti_join(triploid_heat, triploid_heat_uncharacterized, by = 'gene')

triploid_desiccation_NA              <- with(triploid_desiccation, subset(triploid_desiccation, subset = grepl(glob2rx("LOCNA*"), gene)))
triploid_desiccation                 <- anti_join(triploid_desiccation, triploid_desiccation_NA, by = 'gene')
triploid_desiccation_uncharacterized <- with(triploid_desiccation, subset(triploid_desiccation, subset = grepl(grx, description)))
triploid_desiccation_characterized   <- anti_join(triploid_desiccation, triploid_desiccation_uncharacterized, by = 'gene')


# Count number of uncharacterized genes
uncharacterized <- data.frame(known = rep(0, 7), 
                              unknown = rep(0, 7), 
                              percent_unknown = rep(0, 7))

uncharacterized$known <- c(nrow(control_ploidy_characterized),
                           nrow(heat_ploidy_characterized),
                           nrow(desiccation_ploidy_characterized),
                           nrow(diploid_heat_characterized),
                           nrow(diploid_desiccation_characterized),
                           nrow(triploid_heat_characterized),
                           nrow(triploid_desiccation_characterized))

uncharacterized$unknown <- c(nrow(control_ploidy_uncharacterized),
                           nrow(heat_ploidy_uncharacterized),
                           nrow(desiccation_ploidy_uncharacterized),
                           nrow(diploid_heat_uncharacterized),
                           nrow(diploid_desiccation_uncharacterized),
                           nrow(triploid_heat_uncharacterized),
                           nrow(triploid_desiccation_uncharacterized))

uncharacterized$percent_unknown <- (uncharacterized$unknown / (uncharacterized$unknown + uncharacterized$known))

row.names(uncharacterized) <- c('control_ploidy',
                                'heat_ploidy', 
                                'desiccation_ploidy', 
                                'diploid_heat', 
                                'diploid_desiccation', 
                                'triploid_heat', 
                                'triploid_desiccation')

write.table(uncharacterized, file = "../gene_tables/uncharacterized_stats.txt", sep = ",", quote = FALSE, row.names = TRUE)

```

```{R}

write.table(control_ploidy_characterized,       file = "../gene_tables/control_ploidy_characterized.txt",       sep = ",", quote = FALSE, row.names = F)
write.table(heat_ploidy_characterized,          file = "../gene_tables/heat_ploidy_characterized.txt",          sep = ",", quote = FALSE, row.names = F)
write.table(desiccation_ploidy_characterized,   file = "../gene_tables/desiccation_ploidy_characterized.txt",   sep = ",", quote = FALSE, row.names = F)
write.table(diploid_heat_characterized,         file = "../gene_tables/diploid_heat_characterized.txt",         sep = ",", quote = FALSE, row.names = F)
write.table(diploid_desiccation_characterized,  file = "../gene_tables/diploid_desiccation_characterized.txt",  sep = ",", quote = FALSE, row.names = F)
write.table(triploid_heat_characterized,        file = "../gene_tables/triploid_heat_characterized.txt",        sep = ",", quote = FALSE, row.names = F)
write.table(triploid_desiccation_characterized, file = "../gene_tables/triploid_desiccation_characterized.txt", sep = ",", quote = FALSE, row.names = F)

write.table(control_ploidy_uncharacterized,       file = "../gene_tables/control_ploidy_uncharacterized.txt",       sep = ",", quote = FALSE, row.names = F)
write.table(heat_ploidy_uncharacterized,          file = "../gene_tables/heat_ploidy_uncharacterized.txt",          sep = ",", quote = FALSE, row.names = F)
write.table(desiccation_ploidy_uncharacterized,   file = "../gene_tables/desiccation_ploidy_uncharacterized.txt",   sep = ",", quote = FALSE, row.names = F)
write.table(diploid_heat_uncharacterized,         file = "../gene_tables/diploid_heat_uncharacterized.txt",         sep = ",", quote = FALSE, row.names = F)
write.table(diploid_desiccation_uncharacterized,  file = "../gene_tables/diploid_desiccation_uncharacterized.txt",  sep = ",", quote = FALSE, row.names = F)
write.table(triploid_heat_uncharacterized,        file = "../gene_tables/triploid_heat_uncharacterized.txt",        sep = ",", quote = FALSE, row.names = F)
write.table(triploid_desiccation_uncharacterized, file = "../gene_tables/triploid_desiccation_uncharacterized.txt", sep = ",", quote = FALSE, row.names = F)

write.table(control_ploidy$gene,       file = "../gene_tables/control_ploidy_all_LOCID.txt",      sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(heat_ploidy$gene,          file = "../gene_tables/heat_ploidy_all_LOCID.txt",         sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(desiccation_ploidy$gene,   file = "../gene_tables/desiccation_ploidy_all_LOCID.txt",  sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(diploid_heat$gene,         file = "../gene_tables/diploid_heat_all_LOCID.txt",  sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(diploid_desiccation$gene,  file = "../gene_tables/diploid_desiccation_all_LOCID.txt",  sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(triploid_heat$gene,        file = "../gene_tables/triploid_heat_all_LOCID.txt",        sep = ",", quote = FALSE, row.names = F, col.names = F)
write.table(triploid_desiccation$gene, file = "../gene_tables/triploid_desiccation_all_LOCID.txt", sep = ",", quote = FALSE, row.names = F, col.names = F)


```

```{r}
Volcano plots 
ggplot(genes, aes(x = log2FoldChange, y = -log10(pvalue))) +
  geom_point(aes(color = Significant)) +
  scale_color_manual(values = c("red", "grey")) +
  theme_bw(base_size = 12) + theme(legend.position = "bottom") +
  geom_text_repel(
    data = subset(genes, padj < 0.05),
    aes(label = Gene),
    size = 5,
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.3, "lines")

```
